---
- name: "get arch name"
  set_fact:
    etcd_arch: amd64
  when: ansible_architecture == "x86_64"
- name: "get arch name"
  set_fact:
    etcd_arch: arm64
  when: ansible_architecture == "aarch64"
- name: "download etcd"
  get_url:
    url: "https://github.com/etcd-io/etcd/releases/download/v{{ etcd_version }}/etcd-v{{ etcd_version }}-linux-{{ etcd_arch }}.tar.gz"
    dest: "/tmp/etcd-v{{ etcd_version }}-linux-{{ etcd_arch }}.tar.gz"
- name: "unpack etcd"
  unarchive:
    remote_src: yes
    src: "/tmp/etcd-v{{ etcd_version }}-linux-{{ etcd_arch }}.tar.gz"
    dest: /tmp/
- name: "copy etcd"
  copy:
    remote_src: yes
    src: "/tmp/etcd-v{{ etcd_version }}-linux-{{ etcd_arch }}/{{ item }}"
    dest: /usr/local/bin/
    mode: '0755'
  loop:
    - etcd
    - etcdctl
