Vagrant.configure(2) do |config|
  N = 2

  #Iterate over nodes
  (1..N).each do |node_id|
    nid = (node_id - 1)

    config.vm.define "node#{nid}" do |node|
      node.vm.box = "generic/debian11"
      node.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
      end
      node.vm.hostname = "node#{nid}"
      node.vm.network :private_network, ip: "192.168.56.#{200 + nid}"

      if node_id == N
        node.vm.provision "ansible" do |ansible|
          ansible.limit = "all"
          ansible.groups = { }
          ansible.playbook = "playbook.yml"
          ansible.host_vars = {
              "node0" => { "etcd" => true, "interface" => "eth1" },
              "node1" => { "etcd" => true, "interface" => "eth1" },
              "node2" => { "etcd" => true, "interface" => "eth1" },
              "node3" => { "etcd" => true, "interface" => "eth1" },
          }
        end
      end
    end
  end
end

